@startuml
'https://plantuml.com/sequence-diagram

autonumber

onpolicy -> collector: collect()

loop for epoch in range(1 + start_epoch, 1 + max_epoch)
    loop while t.n < t.total:
        alt train_fn
            onpolicy -> onpolicy: train_fn(epoch, env_step)
        end
        onpolicy --> collector: collect()
        onpolicy --> policy: policy.update()
        alt test_collector is not None
            onpolicy -> onpolicy: test_episode()
        end
    end
    alt test_collector is None and save_fn
        onpolicy -> onpolicy: save_fn(policy)
    end
end


@enduml